spring:
  datasource:
    dynamic:
      primary: slave # 设置默认的数据源或者主数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/huadea?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
          username: root
          password: hda@2014
          driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            validation-query: SELECT 1 FROM DUAL
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            max-evictable-idle-time-millis: 300000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            use-global-data-source-stat: true
        slave:
          url: jdbc:mysql://localhost:3306/huadea?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
          username: root
          password: hda@2014
          driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            validation-query: SELECT 1 FROM DUAL
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            max-evictable-idle-time-millis: 300000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            use-global-data-source-stat: true
